### ISSUE TITLE
Support for Next.js v12.2

### ISSUE THREAD

**Issue by aiji42** [aiji42/next-qs-props#115]

**Comment by jeanhdev** [comment]
Hey aiji! 
Is it incompatible or does it work with 12.2 ?

**Comment by aiji42** [comment]
I don't know exactly because I haven't tried it yet either.
However, the middleware specs have changed significantly in v12.2, so I am assuming it will not work.
https://nextjs.org/docs/messages/middleware-upgrade-guide

**Comment by 23233** [comment]
v12.2 is not Work!
