### ISSUE TITLE
Warning: Prop `href` did not match. Server:

### ISSUE THREAD

**Issue by Rest95** [aiji42/next-qs-props#26]
Hi, i've been following you package development and i managed to set every thing up correctly.

But I've been fighting with this error message since the beginning. 

Did this happen to you as well or you have any idea how to fix it?

Warning: Prop `href` did not match. Server: "/categories/new-collection/query.%7B%22order_by%22:%22our_choices%22%7D?order_by=our_choices" Client: "/categories/new-collection?order_by=our_choices"

Thanks in advance :)

**Comment by aiji42** [comment]
Hi @Rest95,

Thanks for installing `next-qs-props`.
I haven't seen such a warning in my case, but that is a typical warning when there is a rendering difference between the server side and the client side.

If you present me with a sample code of a page where the warning is occurring, I may be able to advise you.

**Comment by Rest95** [comment]
Hi @aiji42 

Here is my code :)

_middleware.js
`
    import { makeQueryStringMiddleware } from "qs-props";

    export const middleware = makeQueryStringMiddleware({
      allowKeys: ["attr_tamanhos", "order_by"],
    });

`

[...query].js
getStaticPaths:
`
  export const getStaticPaths = async ({ locales }) => {

    let paths = [];
    for (const locale of locales) {
      const res = await fetch(
      ´${process.env.NEXT_PUBLIC_API_URL}categories/frontendfind?_locale=${locale}´
      );
      const data = await res.json();
      
      paths = [
        ...paths,
        ...data.map((category) => {
        return {
          params: {
          query: [
            category.slug.toString().replace(´-${locale.toLowerCase()}´, ""),
            "query",
          ],
        },
          locale: locale,
        };
        }),
      ];
    }
    
    return {
      paths: paths,
      fallback: "blocking",
    };
    }

  };
`

getStaticProps

`
  export const getStaticProps = async (context) => {

    const params = getQueryStringProps(context, "query");
    console.log(params);
    const queryParams = {};
    // const queryParams = getQuery(context.params);
    const { query } = context.params;
    if (query.length === 0) {
      return {
        notFound: true,
      };
    }
  ...

  };

`

Every time i access to the route without query params i don't get the error message, but when i pass one or more parameter, it shows again. 😕

**Comment by aiji42** [comment]
Please tell me the code for the page component. (That warning should be occurring in the page component.)

**Comment by Rest95** [comment]
Hi @aiji42,

Here are the files:
https://pastebin.com/GxPtSQGC - [...query].js
https://pastebin.com/GB06VhUF - CategoriesQuery.js

I've moved 'get statics' to another file to shorten the page file!

**Comment by aiji42** [comment]
![スクリーンショット 2021-12-10 午後11 41 03](https://user-images.githubusercontent.com/6711766/145591602-00cb864f-6911-491c-9ef6-9a01b4da76d3.png)

If you use `query` of `useRouter` to generate URL(path), the result will be different between server side and client side.
You can eliminate the difference by passing the data obtained by getQueryStringProps as props to the page component and using that data when generating the URL.
I didn't see anything in the code you shared that would cause the difference, but perhaps you are generating the URLs in these components? `import { FiltersModal, ProductCard, ShopHeader } from "../../components"`
